### ISSUE TITLE
Couldnt find a way to private message you

### ISSUE THREAD

**Issue by nibblebits** [monzurularash/OPENSSL-Verification-Certificate-and-CRL#1]
Hello Monzurlarsh,

I couldn't find a way to message you, I am letting you know I deleted your comment on my commit on PeachOS because this commit log is used as a way for people to compare their own code to the code they wrote in the video. Comments will confuse people. If you have found a bug in PeachOS feel free to create a new issue, just as I have on this repository.

I can then look into it further 

Please don't submit any pull requests as the PeachOS repository is made strictly for following the video material, therefore the repository's must match with the one at the end of the video content.

Thanks,
Dan

**Comment by monzurularash** [comment]
Thanks for letting me know. I will check again and raise an issue if necessary.
Thanks,
Monzurul.
